import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {CATALOG} from '../app/catalog.js';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--enable-unsafe-swiftshader']});
const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const nav=async(name)=>{await page.locator(`.nav [data-route="${name}"]`).click();};
try{
 await page.goto('http://127.0.0.1:4180');await page.locator('[data-action="start"]').click();await page.waitForSelector('#pet-host[data-ready="rabbit"]');await page.waitForTimeout(500);await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await page.locator('[data-action="workout"][data-sport="running"]').click();await page.locator('[name=duration]').fill('30');await page.locator('[name=distance]').fill('5');await page.locator('[name=notes]').fill('轻松跑，<测试>\n今天很好');await page.locator('button[form="workout-form"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.match(await page.locator('main').innerText(),/5.00 km/);
 await page.reload();await page.waitForSelector('.nav');assert.match(await page.locator('main').innerText(),/5.00 km/);
 await page.locator('[data-action="workout"][data-sport="cycling"]').click();await page.locator('[name=duration]').fill('60');await page.locator('[name=distance]').fill('20');await page.locator('button[form="workout-form"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
 await page.locator('[data-action="workout"][data-sport="basketball"]').click();await page.locator('[name=start]').fill('2025-12-01T23:30');await page.locator('[name=end]').fill('2025-12-02T00:30');await page.locator('button[form="workout-form"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
 await page.locator('[data-action="workout"][data-sport="strength"]').click();await page.locator('[name=duration]').fill('45');await page.locator('#exercise-picker').selectOption('bench');await page.locator('[data-action=add-exercise]').click();await page.locator('[name=weight-0-0]').fill('40');await page.locator('[name=done-0-0]').check();await page.locator('[name=weight-0-1]').fill('45');await page.locator('[name=done-0-1]').check();await page.locator('[data-action=save-template]').click();await page.locator('[name=name]').fill('胸部日');await page.locator('button[form=template-form]').click();await page.locator('button[form=workout-form]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
 await nav('records');await page.locator('[data-action=calendar-all]').click();assert.match(await page.locator('main').innerText(),/篮球/);assert.match(await page.locator('main').innerText(),/40 kg × 10/);await page.screenshot({path:'test-results/records-desktop.png',fullPage:true});
 await nav('meals');await page.locator('[data-action=meal]').first().click();await page.locator('[name=notes]').fill('朋友聚餐');await page.locator('button[form=meal-form]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.match(await page.locator('main').innerText(),/朋友聚餐/);
 await nav('settings');const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export-json]').click();const backup=await downloadPromise;await backup.saveAs('test-results/roundtrip.json');await page.locator('#import-file').setInputFiles('test-results/roundtrip.json');await page.locator('#replace-ack').check();await page.locator('[data-action=import-confirm]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
 await nav('pets');for(const p of CATALOG){await page.locator(`[data-action=preview][data-id="${p.id}"]`).click();await page.waitForSelector(`#pet-host[data-ready="${p.id}"]`);await page.waitForTimeout(80);await page.locator('#pet-host').screenshot({path:`test-results/pet-${p.id}.png`});}
 await page.setViewportSize({width:390,height:844});for(const route of ['home','records','pets','meals','settings']){await nav(route);if(['home','pets'].includes(route))await page.waitForSelector('#pet-host[data-ready]');await page.waitForTimeout(100);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${route} mobile overflow`);await page.screenshot({path:`test-results/${route}-mobile.png`,fullPage:true});}
 await nav('home');await page.locator('[data-action=workout][data-sport=running]').click();await page.locator('[name=duration]').fill('22');await page.locator('[name=distance]').fill('3.5');await page.locator('[data-action=close]').click();await page.reload();await page.locator('[data-action=resume]').click();assert.equal(await page.locator('[name=distance]').inputValue(),'3.5');await page.locator('[data-action=close]').click();
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForSelector('.nav');await page.context().setOffline(true);await page.reload();await page.waitForSelector('.nav');await nav('pets');await page.locator('[data-action=preview][data-id=whale]').click();await page.waitForSelector('#pet-host[data-ready=whale]');await page.context().setOffline(false);
 assert.deepEqual(errors,[]);console.log('PASS: four sports, sets, template, meal, persistence, JSON restore, 24 companions (22 animated, 2 clearly marked pending), 5 mobile routes, saved draft, offline app + animation; no JS/request errors.');
}finally{await browser.close();}
