import {test} from 'node:test';import assert from 'node:assert/strict';
import {initialState,addDays,weekOf,nextWeek,settleWeek,recompute,unlock,equip,exportBackup,importBackup,validateState,workoutCSV,uid} from '../app/core.js';
const created=new Date('2024-01-01T00:00:00Z'),now='2026-10-02';
function base(){return initialState('rabbit',created);}
function weeks(s,counts){counts.forEach((count,i)=>{const week=addDays(s.scoring_rules.start_week,i*7);for(let j=0;j<count;j++)s.meals.push({id:uid(),date:week,notes:'测试餐',created_at:created.toISOString(),updated_at:created.toISOString()});settleWeek(s,week,now);});return s;}
test('Beijing week boundary and next full week',()=>{assert.equal(weekOf('2026-10-04'),'2026-09-28');assert.equal(nextWeek('2026-10-05'),'2026-10-12');assert.equal(initialState('rabbit',new Date('2026-10-04T16:01:00Z')).scoring_rules.start_week,'2026-10-12');});
test('success, failure, switch and independent balances',()=>{const s=weeks(base(),[0,1,2,3,0]);assert.deepEqual(s.settlements.map(w=>w.delta),['1','2','-2','-4','1']);assert.equal(s.total_score,'58');assert.equal(s.pets[0].score,'58');});
test('missing weeks cannot be skipped and settlement cannot repeat',()=>{const s=base();assert.throws(()=>settleWeek(s,addDays(s.scoring_rules.start_week,7),now));settleWeek(s,s.scoring_rules.start_week,now);assert.throws(()=>settleWeek(s,s.scoring_rules.start_week,now));assert.throws(()=>settleWeek(s,weekOf(now),now));});
test('zero clamps independently and changing equipped pet preserves historical recipients',()=>{const s=weeks(base(),Array(6).fill(0));unlock(s,'eagle');equip(s,'eagle');const w=addDays(s.scoring_rules.start_week,42);for(let i=0;i<2;i++)s.meals.push({id:uid(),date:w,notes:'',created_at:created.toISOString(),updated_at:created.toISOString()});settleWeek(s,w,now);assert.equal(s.pets[1].score,'0');assert.equal(s.total_score,'121');assert.equal(s.pets[0].score,'123');equip(s,'rabbit');s.meals=s.meals.filter(m=>m.date!==w);recompute(s);assert.equal(s.settlements.at(-1).pet_id,'eagle');assert.equal(s.pets[1].score,'64');assert.equal(s.pets[0].score,'123');});
test('historical corrections retain permanent unlock and unique entitlement',()=>{const s=weeks(base(),Array(6).fill(0));unlock(s,'eagle');assert.throws(()=>unlock(s,'ox'));for(let i=0;i<2;i++)s.meals.push({id:uid(),date:s.scoring_rules.start_week,notes:'',created_at:created.toISOString(),updated_at:created.toISOString()});recompute(s);assert.equal(s.pets.length,2);assert.ok(BigInt(s.pets[0].score)<120n);assert.equal(s.pets[0].claimed,true);validateState(s,now);});
test('exact unbounded integer scores survive JSON roundtrip beyond float precision',()=>{const s=weeks(base(),Array(90).fill(0));const expected=60n+(2n**90n-1n);assert.equal(s.total_score,String(expected));const restored=importBackup(exportBackup(s));assert.equal(restored.total_score,s.total_score);assert.equal(restored.pets[0].score,s.pets[0].score);});
test('backup restores year of records, template references, quotes, newline and custom exercise',()=>{const s=base();s.exercises.push({id:'custom',name:'自定义“划船”',muscle:'背',weight_basis:'器械标重',instruction:'说明\n第二行',diagram:'custom',builtin:false});s.templates.push({id:'template',name:'=训练计划',exercises:[{exercise_id:'custom',target_sets:2,target_reps:12}]});for(let i=0;i<365;i++){const sport=['strength','running','cycling','basketball'][i%4],date=addDays('2024-01-01',i);s.workouts.push({id:'w'+i,sport,date,duration_seconds:sport==='basketball'?7200:1800,duration_source:sport==='basketball'?'time_range':'manual',started_at:sport==='basketball'?date+'T23:00:00+08:00':null,ended_at:sport==='basketball'?addDays(date,1)+'T01:00:00+08:00':null,distance_meters:['running','cycling'].includes(sport)?5000:null,notes:sport==='basketball'?'':`=中文,\"\n${i}`,created_at:created.toISOString(),updated_at:created.toISOString(),template_id:sport==='strength'?'template':null,exercises:sport==='strength'?[{exercise_id:'custom',name:'历史动作名',weight_basis:'器械标重',sets:[{id:uid(),weight_kg:12.5,reps:12,completed:true},{id:uid(),weight_kg:0,reps:8,completed:false}]}]:[]});}const restored=importBackup(exportBackup(s));assert.deepEqual(restored.workouts,s.workouts);assert.deepEqual(restored.templates,s.templates);const csv=workoutCSV(s);assert.ok(csv.includes("'=中文"));assert.ok(csv.includes('"12.5"'));});
test('bad imports reject future schema, duplicate IDs, orphan sets, invalid dates and settlements',()=>{for(const change of [s=>s.schema_version='99',s=>s.exercises.push(s.exercises[0]),s=>s.meals.push({id:'m',date:'2024-02-31',notes:'',created_at:created.toISOString(),updated_at:created.toISOString()}),s=>s.settlements.push({week:s.scoring_rules.start_week,pet_id:'ghost',confirmed_at:created.toISOString()}),s=>s.pets[0].threshold='1']){const s=base();change(s);assert.throws(()=>importBackup(JSON.stringify(s)));}});
