import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {initialState,today,weekOf,addDays,exportBackup,uid} from '../app/core.js';
await mkdir('test-results',{recursive:true});const start=addDays(weekOf(today()),-56);const s=initialState('rabbit',new Date(start+'T00:00:00+08:00'));const failure=addDays(s.scoring_rules.start_week,42);for(let i=0;i<2;i++)s.meals.push({id:uid(),date:failure,notes:'虚构超标周',created_at:s.created_at,updated_at:s.created_at});await writeFile('test-results/settlement-fixture.json',exportBackup(s));
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
try{const context=await browser.newContext(),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4180');await page.locator('[data-action=onboard-import]').click();await page.locator('#import-file').setInputFiles('test-results/settlement-fixture.json');await page.locator('#replace-ack').check();await page.locator('[data-action=import-confirm]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);const read=()=>page.evaluate(async()=>{const {readState}=await import('./store.js');return readState();});assert.equal((await read()).total_score,'60');await page.locator('.nav [data-route=meals]').click();
 for(let i=0;i<6;i++){await page.locator('[data-action=settlement]').click();await page.locator('[data-action=settlement-confirm]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);}assert.equal((await read()).total_score,'123');
 await page.locator('.nav [data-route=pets]').click();await page.locator('[data-action=preview][data-id=eagle]').click();await page.locator('[data-action=unlock]').click();await page.locator('[data-action=equip]').click();await page.waitForFunction(async()=>{const {readState}=await import('./store.js');return (await readState()).equipped==='eagle';});await page.locator('.nav [data-route=meals]').click();await page.locator('[data-action=settlement]').click();await page.locator('[data-action=settlement-confirm]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);let stored=await read();assert.equal(stored.total_score,'121');assert.equal(stored.pets[1].score,'0');assert.equal(stored.pets[0].score,'123');
 for(let i=0;i<2;i++){await page.locator('[data-action=meal]').first().click();await page.locator('[name=date]').fill(s.scoring_rules.start_week);await page.locator('button[form=meal-form]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);}stored=await read();assert.equal(stored.total_score,'87');assert.equal(stored.pets[0].score,'89');assert.equal(stored.pets.length,2);assert.equal(stored.settlements.at(-1).pet_id,'eagle');await page.screenshot({path:'test-results/settlement-history.png',fullPage:true});
 const second=await context.newPage();await second.goto('http://127.0.0.1:4180');const rev=stored.revision;const write=pg=>pg.evaluate(async revision=>{const {readState,writeState}=await import('./store.js');const s=await readState();try{await writeState(s,revision);return true;}catch{return false;}},rev);const results=await Promise.all([write(page),write(second)]);assert.equal(results.filter(Boolean).length,1);assert.deepEqual(errors,[]);console.log('PASS: zero-week confirmation, 6-week exact rewards, unlock + equip, independent zero floor, UI historical correction, permanent unlock, stable recipient, simultaneous-tab revision protection.');
}finally{await browser.close();}
