import {CATALOG} from './catalog.js';
import {EXERCISES} from './exercises.js';
export const VERSION='1.0.0';
export const uid=()=>crypto.randomUUID();
export const today=(now=new Date())=>new Date(+now+8*3600000).toISOString().slice(0,10);
export const addDays=(date,n)=>new Date(Date.parse(date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export function weekOf(date){const day=new Date(date+'T00:00:00Z').getUTCDay();return addDays(date,-((day+6)%7));}
export const nextWeek=date=>addDays(weekOf(date),7);
export const stamp=()=>new Date().toISOString();
export function initialState(petId='rabbit',now=new Date()){return {schema_version:VERSION,app_version:'0.1.0',created_at:now.toISOString(),revision:0,settings:{rest_seconds:90,time_zone:'Asia/Shanghai'},scoring_rules:{version:'weekly-v1',start_week:nextWeek(today(now)),growth_version:'growth-draft-v1'},equipped:petId,exercises:structuredClone(EXERCISES),workouts:[],templates:[],meals:[],settlements:[],pets:[{id:petId,initial_score:'60',score:'60',threshold:'120',unlocked_at:now.toISOString(),source:null,claimed:false}],equipment_events:[{pet_id:petId,at:now.toISOString()}],total_score:'60',draft:null};}
export function mealCount(s,week){return s.meals.filter(m=>weekOf(m.date)===week).length;}
export function pendingWeeks(s,date=today()){const result=[];const settled=new Set(s.settlements.map(w=>w.week));for(let w=s.scoring_rules.start_week;w<weekOf(date);w=addDays(w,7))if(!settled.has(w))result.push(w);return result;}
export function recompute(s){let total=60n,last=null,streak=0;const scores=Object.fromEntries(s.pets.map(p=>[p.id,BigInt(p.initial_score)]));s.settlements.sort((a,b)=>a.week.localeCompare(b.week));for(const row of s.settlements){const count=mealCount(s,row.week),success=count<=1;streak=last===success?streak+1:1;last=success;const delta=success?2n**BigInt(streak-1):-(2n**BigInt(streak));const before=total,petBefore=scores[row.pet_id];if(petBefore===undefined)throw Error('周结算引用了不存在的精灵');total=before+delta<0n?0n:before+delta;scores[row.pet_id]=petBefore+delta<0n?0n:petBefore+delta;Object.assign(row,{count,success,streak,delta:String(delta),total_before:String(before),total_after:String(total),total_actual:String(total-before),pet_before:String(petBefore),pet_after:String(scores[row.pet_id]),pet_actual:String(scores[row.pet_id]-petBefore)});}s.total_score=String(total);s.pets.forEach(p=>p.score=String(scores[p.id]));return s;}
export function settleWeek(s,week,date=today()){if(pendingWeeks(s,date)[0]!==week)throw Error('请按时间顺序确认已结束的周，不能重复结算');s.settlements.push({week,pet_id:s.equipped,confirmed_at:stamp()});return recompute(s);}
export function unlock(s,id){if(!CATALOG.some(p=>p.id===id)||s.pets.some(p=>p.id===id))throw Error('该精灵不可解锁');const source=s.pets.find(p=>!p.claimed&&BigInt(p.score)>=BigInt(p.threshold));if(!source)throw Error('伙伴首次满级后，可领养一位新伙伴');source.claimed=true;s.pets.push({id,initial_score:'0',score:'0',threshold:String(120n*2n**BigInt(s.pets.length)),unlocked_at:stamp(),source:source.id,claimed:false});}
export function equip(s,id){if(!s.pets.some(p=>p.id===id))throw Error('请先解锁这位伙伴');s.equipped=id;s.equipment_events.push({pet_id:id,at:stamp()});}
export function summarize(workouts){const result={days:new Set(workouts.map(w=>w.date)).size,seconds:0,count:workouts.length,distance:0,bySport:{}};for(const w of workouts){result.seconds+=w.duration_seconds;result.distance+=w.distance_meters||0;const a=result.bySport[w.sport]??={count:0,seconds:0,distance:0};a.count++;a.seconds+=w.duration_seconds;a.distance+=w.distance_meters||0;}return result;}
const require=(test,message)=>{if(!test)throw Error(message);};
const isDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const text=(v,n=2000)=>typeof v==='string'&&v.length<=n;
const number=(v,min=0,max=1e9)=>Number.isFinite(v)&&v>=min&&v<=max;
const integer=(v,min=0,max=1e9)=>Number.isInteger(v)&&v>=min&&v<=max;
const score=v=>typeof v==='string'&&/^(0|[1-9]\d*)$/.test(v)&&v.length<=10000;
const timestamp=v=>typeof v==='string'&&v.length<50&&Number.isFinite(Date.parse(v));
function ids(list,name){require(Array.isArray(list)&&list.length<=100000,`${name}不是有效列表`);const used=new Set();for(const r of list){require(r&&text(r.id,100)&&r.id.length&&!used.has(r.id),`${name} ID 缺失或重复`);used.add(r.id);}return used;}
export function validateWorkout(w,exerciseIds){require(w&&text(w.id,100)&&['strength','running','cycling','basketball'].includes(w.sport),'运动类型或 ID 无效');require(isDate(w.date),'运动日期无效');require(number(w.duration_seconds,1,604800),'运动时长须大于 0 且不超过 7 天');require(text(w.notes),'备注无效');require(['manual','timer','time_range'].includes(w.duration_source),'时长来源无效');require(timestamp(w.created_at)&&timestamp(w.updated_at),'运动时间戳无效');require(w.started_at===null||timestamp(w.started_at),'开始时间无效');require(w.ended_at===null||timestamp(w.ended_at),'结束时间无效');if(w.sport==='basketball'){require(w.notes===''&&timestamp(w.started_at)&&timestamp(w.ended_at)&&(+new Date(w.ended_at)-new Date(w.started_at))/1000===w.duration_seconds,'篮球起止时间与时长不一致');require(today(new Date(w.started_at))===w.date,'篮球日期与开始时间不一致');}if(['running','cycling'].includes(w.sport))require(number(w.distance_meters,.1,1e7),'距离须大于 0');else require(w.distance_meters===null,'非跑骑运动不能带距离');require(Array.isArray(w.exercises),'训练动作无效');if(w.sport==='strength'){require(w.exercises.length>0&&w.exercises.length<=100,'至少添加一个动作');const allSets=new Set();for(const e of w.exercises){require(exerciseIds.has(e.exercise_id)&&text(e.name)&&text(e.weight_basis,100),'训练动作引用或快照无效');require(Array.isArray(e.sets)&&e.sets.length>0&&e.sets.length<=100,'动作至少一组');for(const set of e.sets){require(text(set.id,100)&&!allSets.has(set.id),'组 ID 重复');allSets.add(set.id);require(integer(set.reps,1,10000)&&number(set.weight_kg,0,5000)&&typeof set.completed==='boolean','组数、重量或完成状态无效');}}}else require(w.exercises.length===0,'非力量运动不能包含逐组数据');}
export function validateState(s,date=today()){
 require(s&&s.schema_version===VERSION,'不支持此备份版本');require(timestamp(s.created_at)&&today(new Date(s.created_at))<=date,'创建日期无效或晚于今天');
 require(s.settings?.time_zone==='Asia/Shanghai'&&integer(s.settings.rest_seconds,5,3600),'设置无效');
 require(s.scoring_rules?.version==='weekly-v1'&&s.scoring_rules.growth_version==='growth-draft-v1'&&s.scoring_rules.start_week===nextWeek(today(new Date(s.created_at))),'计分规则或启用周无效');
 const exerciseIds=ids(s.exercises,'动作');for(const e of s.exercises)require(text(e.name,100)&&e.name.trim()&&text(e.weight_basis,100)&&text(e.muscle,100)&&typeof e.builtin==='boolean'&&text(e.instruction)&&text(e.diagram,30),'动作定义无效');
 ids(s.workouts,'运动');s.workouts.forEach(w=>validateWorkout(w,exerciseIds));
 ids(s.templates,'模板');for(const t of s.templates){require(text(t.name,100)&&t.name.trim()&&Array.isArray(t.exercises)&&t.exercises.length>0&&t.exercises.length<=100,'模板无效');for(const e of t.exercises)require(exerciseIds.has(e.exercise_id)&&integer(e.target_sets,1,100)&&integer(e.target_reps,1,10000),'模板动作或目标无效');}
 ids(s.meals,'餐记录');for(const m of s.meals)require(isDate(m.date)&&m.date<=date&&text(m.notes)&&timestamp(m.created_at)&&timestamp(m.updated_at),'餐记录日期或字段无效');
 const petIds=ids(s.pets,'精灵');require(s.pets.length>=1&&s.pets.length<=24&&petIds.has(s.equipped),'装配精灵无效');for(const [i,p] of s.pets.entries()){require(CATALOG.some(c=>c.id===p.id)&&p.initial_score===(i?'0':'60')&&score(p.score)&&p.threshold===String(120n*2n**BigInt(i))&&timestamp(p.unlocked_at)&&typeof p.claimed==='boolean','精灵进度无效');require(i?p.source&&s.pets.slice(0,i).some(a=>a.id===p.source&&a.claimed):p.source===null,'解锁来源无效');}const sources=s.pets.slice(1).map(p=>p.source);require(new Set(sources).size===sources.length&&s.pets.every(p=>p.claimed===sources.includes(p.id)),'解锁资格重复或不一致');
 require(Array.isArray(s.settlements)&&s.settlements.length<=10000,'结算记录无效');const ordered=[...s.settlements].sort((a,b)=>String(a.week).localeCompare(String(b.week)));for(const [i,w] of ordered.entries())require(isDate(w.week)&&w.week===addDays(s.scoring_rules.start_week,i*7)&&w.week<weekOf(date)&&petIds.has(w.pet_id)&&timestamp(w.confirmed_at),'周结算须连续、已结束且精灵归属有效');
 require(Array.isArray(s.equipment_events)&&s.equipment_events.every(e=>petIds.has(e.pet_id)&&timestamp(e.at)),'装配历史无效');require(score(s.total_score),'总分无效');
 // Derived balances are never trusted on import. Original recipients remain unchanged.
 recompute(s);if(s.draft!==null){const d=s.draft;require(d&&['strength','running','cycling','basketball'].includes(d.sport)&&[d.date,d.duration,d.distance,d.start,d.end,d.notes].every(v=>text(v))&&Array.isArray(d.exercises)&&d.exercises.length<=100,'训练草稿字段无效');require(d.id===null||s.workouts.some(w=>w.id===d.id),'草稿原记录不存在');require(d.started_at===null||timestamp(d.started_at),'草稿计时无效');require(d.ended_at===null||timestamp(d.ended_at),'草稿计时无效');for(const e of d.exercises){require(exerciseIds.has(e.exercise_id)&&text(e.name)&&text(e.weight_basis)&&Array.isArray(e.sets)&&e.sets.length<=100,'草稿动作无效');for(const a of e.sets)require(text(a.id,100)&&text(a.weight,100)&&text(a.reps,100)&&typeof a.completed==='boolean','草稿逐组字段无效');}}return s;
}
export function exportBackup(s){const out=structuredClone(s);delete out.revision;out.exported_at=stamp();out.format_notes='AllenOne 1.0.0; scores are decimal strings; kg/meters/seconds; dates Asia/Shanghai. See DATA_FORMAT.md.';return JSON.stringify(out,null,2);}
export function importBackup(raw){require(raw.length<=20*1024*1024,'备份超过 20 MB，请拆分迁移处理');return validateState(JSON.parse(raw));}
function cell(value){let v=value==null?'':String(value);if(/^[=+\-@\t\r']/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';}
export function workoutCSV(s){const rows=[['workout_id','sport','date','duration_seconds','distance_meters','notes','exercise_index','exercise_id','exercise_name','set_id','set_index','weight_kg','weight_basis','reps','completed']];for(const w of s.workouts){const base=[w.id,w.sport,w.date,w.duration_seconds,w.distance_meters,w.notes];if(w.sport!=='strength')rows.push(base);else w.exercises.forEach((e,i)=>e.sets.forEach((set,j)=>rows.push([...base,i,e.exercise_id,e.name,set.id,j,set.weight_kg,e.weight_basis,set.reps,set.completed])));}return '\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n');}
